#!/bin/bash
# ─────────────────────────────────────────────────────────────
# SprintFlow — Server Setup & Deployment Script
# Ubuntu 22.04 | Single server | Docker Compose
#
# Usage (run once on a fresh server):
#   chmod +x setup.sh
#   ./setup.sh
#
# What this script does:
#   1. Installs Docker + Docker Compose plugin
#   2. Generates a self-signed SSL certificate
#   3. Creates .env from .env.example with generated secrets
#   4. Builds and starts all containers
# ─────────────────────────────────────────────────────────────

set -e  # Exit immediately on any error

# ── Colours for output ────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; NC='\033[0m'

info()    { echo -e "${BLUE}▶ $1${NC}"; }
success() { echo -e "${GREEN}✅ $1${NC}"; }
warn()    { echo -e "${YELLOW}⚠  $1${NC}"; }
error()   { echo -e "${RED}❌ $1${NC}"; exit 1; }

# ── Detect server IP ──────────────────────────────────────────
SERVER_IP=$(curl -s --max-time 5 http://checkip.amazonaws.com || \
            curl -s --max-time 5 https://api.ipify.org || \
            hostname -I | awk '{print $1}')

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║         SprintFlow — Docker Deployment Setup         ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
info "Detected server IP: ${SERVER_IP}"
echo ""

# ── Step 1: Install Docker ────────────────────────────────────
info "Step 1/5 — Installing Docker..."

if command -v docker &> /dev/null; then
    success "Docker already installed: $(docker --version)"
else
    sudo apt-get update -qq
    sudo apt-get install -y -qq ca-certificates curl gnupg lsb-release

    # Add Docker's official GPG key
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    sudo apt-get update -qq
    sudo apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
        docker-buildx-plugin docker-compose-plugin

    # Allow current user to run docker without sudo
    sudo usermod -aG docker "$USER"
    success "Docker installed successfully"
fi

# ── Step 2: Generate self-signed SSL certificate ──────────────
info "Step 2/5 — Generating self-signed SSL certificate..."

mkdir -p docker/ssl

if [ -f docker/ssl/sprintflow.crt ] && [ -f docker/ssl/sprintflow.key ]; then
    warn "SSL certificate already exists — skipping generation"
else
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout docker/ssl/sprintflow.key \
        -out    docker/ssl/sprintflow.crt \
        -subj   "/C=IN/ST=State/L=City/O=SprintFlow/CN=${SERVER_IP}" \
        -addext "subjectAltName=IP:${SERVER_IP}" \
        2>/dev/null
    chmod 600 docker/ssl/sprintflow.key
    success "SSL certificate generated for IP: ${SERVER_IP}"
fi

# ── Step 3: Generate secrets and create .env ──────────────────
info "Step 3/5 — Configuring environment variables..."

if [ -f .env ]; then
    warn ".env already exists — skipping creation (delete it to regenerate)"
else
    # Generate cryptographically secure secrets
    JWT_SECRET=$(openssl rand -hex 32)
    MAIL_KEY=$(openssl rand -hex 16)
    DB_PASS=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9!@#' | head -c 20)
    ROOT_PASS=$(openssl rand -base64 16 | tr -dc 'A-Za-z0-9!@#' | head -c 20)

    cat > .env << EOF
# Generated by setup.sh on $(date)
# chmod 600 .env — do not share this file

MYSQL_ROOT_PASSWORD=${ROOT_PASS}
DB_USERNAME=sprintflow
DB_PASSWORD=${DB_PASS}

APP_JWT_SECRET=${JWT_SECRET}
APP_MAIL_KEY=${MAIL_KEY}

APP_CORS_ORIGINS=https://${SERVER_IP}
APP_FRONTEND_URL=https://${SERVER_IP}

VITE_API_BASE_URL=https://${SERVER_IP}/api
VITE_WS_URL=https://${SERVER_IP}

SWAGGER_ENABLED=false
EOF

    chmod 600 .env
    success ".env created with auto-generated secrets"
    echo ""
    warn "IMPORTANT — Save these credentials somewhere safe:"
    echo "  DB Password:  ${DB_PASS}"
    echo "  JWT Secret:   ${JWT_SECRET}"
    echo "  Mail Key:     ${MAIL_KEY}"
    echo ""
fi

# ── Step 4: Build and start containers ────────────────────────
info "Step 4/5 — Building Docker images (this takes 3-5 minutes on first run)..."

# Use docker compose (v2 plugin syntax)
docker compose build --no-cache

success "Images built successfully"

info "Step 5/5 — Starting all containers..."

docker compose up -d

# ── Wait for services to be healthy ──────────────────────────
info "Waiting for services to start..."
sleep 10

# Check container status
echo ""
docker compose ps
echo ""

# ── Final output ──────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              🚀 SprintFlow is running!               ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
success "App URL:    https://${SERVER_IP}"
success "API URL:    https://${SERVER_IP}/api/health"
echo ""
warn "First-time browser warning: Your browser will show a security"
warn "warning for the self-signed certificate. Click 'Advanced' →"
warn "'Proceed to ${SERVER_IP}' to continue."
echo ""
info "Default login: admin@sprintflow.local / Admin@123"
warn "Change the admin password immediately after first login!"
echo ""
info "Useful commands:"
echo "  docker compose logs -f backend    # backend logs"
echo "  docker compose logs -f frontend   # nginx logs"
echo "  docker compose logs -f mysql      # database logs"
echo "  docker compose down               # stop everything"
echo "  docker compose up -d --build      # rebuild and restart"
echo ""
